# Generated by Django 4.1.6 on 2023-03-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='caption',
        ),
    ]
